// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteSkill(arg1:string):Promise<void>;

export function GetAgents():Promise<Array<main.AgentConfig>>;

export function GetSkillDetails(arg1:string):Promise<Array<main.FileInfo>>;

export function GetSkills(arg1:string):Promise<Array<main.SkillInfo>>;
