// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteSkill(arg1) {
  return window['go']['main']['App']['DeleteSkill'](arg1);
}

export function GetAgents() {
  return window['go']['main']['App']['GetAgents']();
}

export function GetSkillDetails(arg1) {
  return window['go']['main']['App']['GetSkillDetails'](arg1);
}

export function GetSkills(arg1) {
  return window['go']['main']['App']['GetSkills'](arg1);
}
